/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EmptyResults: typeof import('./components/EmptyResults.vue')['default']
    FilmCard: typeof import('./components/FilmCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./components/Spinner.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheLogo: typeof import('./components/TheLogo.vue')['default']
    TheMenu: typeof import('./components/TheMenu.vue')['default']
    TheSearchForm: typeof import('./components/TheSearchForm.vue')['default']
    UiButton: typeof import('./components/ui/Button.vue')['default']
    UiIcon: typeof import('./components/ui/Icon.vue')['default']
  }
}
